{
  "main": {
    "files": [
      "$all",
      "!$test",
    ],
    "allow": [
      "$gostd",
      "github.com/gobeam/stringy",
      "github.com/awslabs/goformation/v7/cloudformation/tags",
      "github.com/awslabs/goformation/v7/cloudformation",
      "github.com/rs/zerolog/log",
      "sato/src/arm",
      "sato/src/cf",
      "sato/src/see",
      "sato/tests/utils",
      "github.com/rs/zerolog",
      "github.com/rs/zerolog/log",
      "github.com/urfave/cli/v2",
      "github.com/go-git/go-git/v5",
      "github.com/go-git/go-git/v5/plumbing",
      "github.com/hashicorp/hc-install/product",
      "github.com/hashicorp/hc-install/releases",
      "github.com/hashicorp/terraform-exec/tfexec",
      "github.com/rs/zerolog/log",
    ],
  },
  "tests": {
    "files": [
      "$test",
    ],
    "deny": {
    }
  }
}
