{
  "main": {
    "files": [
      "$all",
      "!$test",
    ],
    "allow": [
      "$gostd",
      "github.com/gobeam/stringy",
      "github.com/awslabs/goformation/v7/cloudformation/tags",
      "github.com/awslabs/goformation/v7/cloudformation",
      "github.com/rs/zerolog/log",
      "sato/src/arm",
      "sato/src/cf",
      "sato/src/see",
      "github.com/rs/zerolog",
      "github.com/rs/zerolog/log",
      "github.com/urfave/cli/v2",
    ],
    "deny": {
    }
  },
  "tests": {
    "files": [
      "$test"
    ],
    "deny": {
    }
  }
}
