// Package ai provides an LLM fallback for resource types that have no
// hand-written .template yet. The converter is asked for two things: the
// concrete HCL for the given resource instance, and a generalised Go
// text/template draft that would produce equivalent HCL from .resource fields.
package ai

import (
	"context"
	"os"
	"path/filepath"
)

// Request describes a single resource that the deterministic path could not
// convert.
type Request struct {
	// SourceType is the upstream type, e.g. "AWS::ACMPCA::Certificate" or
	// "Microsoft.Network/loadBalancers".
	SourceType string
	// TFType is the terraform resource type if known (from see.Lookup); may be
	// empty when the mapping itself is missing.
	TFType string
	// Provider is "aws" or "azurerm".
	Provider string
	// Name is the logical name to use for the resource block label.
	Name string
	// Resource is the raw resource body (goformation struct or ARM map).
	Resource any
}

// Result holds the two artefacts produced by a conversion.
type Result struct {
	// TFType is the terraform resource type the model settled on.
	TFType string
	// HCL is the concrete resource block for this instance.
	HCL string
	// Template is a Go text/template draft generalising HCL over .resource.
	Template string
}

// Converter turns a single unmapped resource into HCL plus a draft template.
type Converter interface {
	Convert(ctx context.Context, req Request) (*Result, error)
}

// Header is prepended to AI-generated .tf output so reviewers can spot it.
const Header = "# AI-generated by sato --ai-fallback. Review before apply.\n"

// WriteDraft saves a generated template draft under <dir>/_drafts/<tfType>.template.
// Existing drafts are overwritten so repeated runs converge on the latest output.
func WriteDraft(dir, tfType, template string) error {
	if template == "" || tfType == "" {
		return nil
	}

	draftDir := filepath.Join(dir, "_drafts")
	if err := os.MkdirAll(draftDir, 0o750); err != nil {
		return err
	}

	path := filepath.Join(draftDir, tfType+".template")
	return os.WriteFile(path, []byte(template), 0o600)
}
