Resources:

  athenworkgroup:
    Type: AWS::Athena::WorkGroup
    Properties:
      Name: "my-workgroup"
      State: "ENABLED"

  securityhubAthenaView:
    Type: AWS::Athena::NamedQuery
    Properties:
      Name: AWS-athena
      Database: !Ref database
      WorkGroup: !Ref athenworkgroup
      QueryString: >
          SELECT * FROM "my_table" WHERE "severity" = 'CRITICAL'

  MyAthenaWorkGroup:
    Type: 'AWS::Athena::WorkGroup'
    Properties:
      Name: "MyCustomWorkGroup"
      Description: "My WorkGroup"
      State: "ENABLED"
      Tags:
        - Key: "key1"
          Value: "value1"
        - Key: "key2"
          Value: "value2"
      WorkGroupConfiguration:
        BytesScannedCutoffPerQuery: 200000000
        EnforceWorkGroupConfiguration: false
        PublishCloudWatchMetricsEnabled: false
        RequesterPaysEnabled: true
        ResultConfiguration:
          OutputLocation: "s3://path/to/my/bucket/"
